##pandas

In [1]:
'''Intro to pandas'''

'Intro to pandas'

In [6]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/smce-sw30/.local/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /home/smce-sw30/.local/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: tzdata>=2022.7 in /home/smce-sw30/.local/lib/python3.10/site-packages (from pandas) (2026.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/smce-sw30/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [10]:
import pandas as pd

df=pd.DataFrame({"Name":["jaga","alex","jack"],
                 "Dept":["cse","ece","Ai"],
                 "CGPA":[9,8.2,7.9]})
print(df)
df[df["CGPA"]>8]

   Name Dept  CGPA
0  jaga  cse   9.0
1  alex  ece   8.2
2  jack   Ai   7.9

   Name Dept  CGPA
0  jaga  cse   9.0
1  alex  ece   8.2

In [2]:
df["email"]=["1334@gmail.com","deesh@gmail.com","jaga@gmail.com"]
print(df)

   Name Dept  CGPA            email
0  jaga  cse   9.0   1334@gmail.com
1  alex  ece   8.2  deesh@gmail.com
2  jack   Ai   7.9   jaga@gmail.com

In [12]:

df.Name

0    jaga
1    alex
2    jack
Name: Name, dtype: object

In [15]:
df[df["CGPA"]>8]

   Name Dept  CGPA
0  jaga  cse   9.0
1  alex  ece   8.2

In [1]:
df[(df["CGPA"]>=9) & (df["email"] == "1334@gmail.com")]

NameError: name 'df' is not defined

In [32]:
import pandas as pd
df=pd.DataFrame({"Name":["jaga","alex","jack"],
                 "Dept":["cse","ece","Ai"], 
                 "CGPA":[9.0,8.2,7.9]}) 
df["email"]=["1334@gmail.com","deesh@gmail.com","jaga@gmail.com"] 
df[(df["CGPA"]>=9) & (df["email"] == "1334@gmail.com")]

   Name Dept  CGPA           email
0  jaga  cse   9.0  1334@gmail.com

In [5]:
df1.shape       
df1["location"].fillna("cbe",inplace=True)
df1["location"].fillna("cbe",inplace=True)


df1["location"].fillna("cbe",inplace=True)

NameError: name 'df' is not defined

In [2]:
df1.columns

NameError: name 'df1' is not defined

In [6]:
                                                                                                       
    df1["location"].fillna("cbe",inplace=True)

/tmp/ipykernel_10464/3936220401.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["location"].fillna("cbe",inplace=True)

SyntaxError: invalid decimal literal (237705286.py, line 3)

In [16]:
import pandas as pd
df = pd.read_csv("order.csv")
a=pd.DataFrame(df)
a

,order_id,user_id,restaurant_id,order_date,total_amount,items_ordered,payment_method,order_status,name_user,gender,city_user,name_restaurant,city_restaurant,avg_cost_for_two,rating,delivery_pertner_pay,delivery_time_min
0,ORD0001,USR002,RST007,01/04/2024,2188,"Fried Rice, Masala Dosa, Hakka Noodles",Credit Card,Completed,Damini Lal,Female,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,153.16000000000003,60.0
1,ORD1933,USR080,RST007,26/03/2025,846,"Chicken Biryani, Dal Makhani, Mutton Rogan Josh",Wallet,Completed,Ela Dubey,Female,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,59.220000000000006,50.0
2,ORD1946,USR038,RST007,28/03/2025,1431,"Chole Bhature, Aloo Tikki, Samosa",Cash on Delivery,Completed,Riaan Thaker,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,100.17000000000002,80.0
3,ORD1265,USR102,RST007,21/11/2024,1231,"Butter Naan, Chicken Curry, Aloo Tikki, Masala...",Wallet,Completed,Vihaan Som,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,86.17,60.0
4,ORD1694,USR124,RST007,09/02/2025,523,"Butter Naan, Chole Bhature, Pav Bhaji",UPI,Completed,Riaan Kata,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,36.61000000000001,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1963,ORD1068,USR125,RST073,12/10/2024,2359,"Chicken Biryani, Chicken Curry, Dal Makhani",UPI,Completed,Hazel Bali,Female,Pune,Tasty Kitchen #73,Pune,429,4.9,165.13000000000002,50.0
1964,ORD0429,USR194,RST073,17/06/2024,0,"Butter Naan, Chicken Curry, Veg Pulao",UPI,Cancelled,Kashvi Sahota,Female,Pune,Tasty Kitchen #73,Pune,429,4.9,137.55,40.0
1965,ORD1438,USR194,RST073,23/12/2024,1879,"Dal Makhani, Aloo Tikki",Cash on Delivery,Completed,Kashvi Sahota,Female,Pune,Tasty Kitchen #73,Pune,429,4.9,131.53,60.0
1966,ORD1325,USR090,RST073,01/12/2024,1397,"Samosa, Mutton Rogan Josh, Veg Pulao, Chicken ...",UPI,Completed,Faiyaz Loke,Male,Pune,Tasty Kitchen #73,Pune,429,4.9,97.79,100.0
1967,ORD1968,USR145,RST046,2025-05-28,560,"Burger, Coke",UPI,Completed,Sivaraman T,Male,Chennai,Spicy Grill #46,Chennai,400,4.4,39.2,40.0

In [19]:
df = pd.read_csv("ordered1.csv")
b=pd.DataFrame(df)
b

,order_id,user_id,restaurant_id,order_date,total_amount,items_ordered,payment_method,order_status,name_user,gender,city_user,name_restaurant,city_restaurant,avg_cost_for_two,rating,delivery_pertner_pay,delivery_time_min
0,ORD0001,USR002,RST007,01/04/2024,2188,"Fried Rice, Masala Dosa, Hakka Noodles",Credit Card,Completed,Damini Lal,Female,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,153.16,60.0
1,ORD1933,USR080,RST007,26/03/2025,846,"Chicken Biryani, Dal Makhani, Mutton Rogan Josh",Wallet,Completed,Ela Dubey,Female,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,59.22,50.0
2,ORD1946,USR038,RST007,28/03/2025,1431,"Chole Bhature, Aloo Tikki, Samosa",Cash on Delivery,Completed,Riaan Thaker,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,100.17,80.0
3,ORD1265,USR102,RST007,21/11/2024,1231,"Butter Naan, Chicken Curry, Aloo Tikki, Masala...",Wallet,Completed,Vihaan Som,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,86.17,60.0
4,ORD1694,USR124,RST007,09/02/2025,523,"Butter Naan, Chole Bhature, Pav Bhaji",UPI,Completed,Riaan Kata,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,36.61,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1963,ORD1068,USR125,RST073,12/10/2024,2359,"Chicken Biryani, Chicken Curry, Dal Makhani",UPI,Completed,Hazel Bali,Female,Pune,Tasty Kitchen #73,Pune,429,4.9,165.13,50.0
1964,ORD0429,USR194,RST073,17/06/2024,0,"Butter Naan, Chicken Curry, Veg Pulao",UPI,Cancelled,Kashvi Sahota,Female,Pune,Tasty Kitchen #73,Pune,429,4.9,137.55,40.0
1965,ORD1438,USR194,RST073,23/12/2024,1879,"Dal Makhani, Aloo Tikki",Cash on Delivery,Completed,Kashvi Sahota,Female,Pune,Tasty Kitchen #73,Pune,429,4.9,131.53,60.0
1966,ORD1325,USR090,RST073,01/12/2024,1397,"Samosa, Mutton Rogan Josh, Veg Pulao, Chicken ...",UPI,Completed,Faiyaz Loke,Male,Pune,Tasty Kitchen #73,Pune,429,4.9,97.79,100.0
1967,ORD1968,USR145,RST046,2025-05-28,560,"Burger, Coke",UPI,Completed,Sivaraman T,Male,Chennai,Spicy Grill #46,Chennai,400,4.4,39.20,40.0